---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox

run:
  path: ./spring-music/gradlew clean assemble

inputs:
  - name: spring-music

outputs:
  - name: build

