---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: aucnet4dev/angular2

run:
  path: ./spring-music/ci/build.sh

inputs:
  - name: spring-music

outputs:
  - name: build

